import '@/assets/styles/global.css'
import '@/assets/styles/styles.css'
import Script from "next/script";
import Navigation from "@/components/Navigation";
import Footer from '@/components/Footer';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
          {children}
          <section className="gradient-background-primary">
              <Footer />
          </section>
        </body>
        <Script src="/js/bootstrap.bundle.js" />
    </html>
  );
}
