import '@/assets/styles/global.css'
import '@/assets/styles/styles.css'
import Script from "next/script";
import Footer from '@/components/Footer'
import NavBar from '@/components/Navbar'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      <body className='wrapper'>
        <NavBar />
          {children}
          <Footer />
        </body>
        <Script src="/js/bootstrap.bundle.js" />
    </html>
  );
}
